[versions]
spring-boot = "4.0.2"
spring-dependency-management = "1.1.7"
lombok = "1.18.42"
spotless = "8.2.1"
checkstyle = "13.2.0"
spotbugs-plugin = "6.4.8"
sonarqube = "7.2.2.6593"

[plugins]
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
spring-dependency-management = { id = "io.spring.dependency-management", version.ref = "spring-dependency-management" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
spotbugs = { id = "com.github.spotbugs", version.ref = "spotbugs-plugin" }
sonarqube = { id = "org.sonarqube", version.ref = "sonarqube" }

[libraries]
lombok = { module = "org.projectlombok:lombok", version.ref = "lombok" }
